version: "3.8"

services:
  db-mysql:
    image: mysql:8.0
    platform: linux/amd64
    hostname: db-mysql
    container_name: db-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF_8
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--default-time-zone=Asia/Seoul"
      - "--sql_mode=IGNORE_SPACE,STRICT_TRANS_TABLES"
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./db-mysql:/var/lib/mysql
